#!/bin/bash

set -eo pipefail

CONFIG=/etc/default/4gpi
TIMEOUT=10
BASE_PATH=/etc/NetworkManager/system-connections/

VERSION="1.0"

USAGE="Usage: 4gpi-nm-helper COMMAND [PARAM...]

Commands:
  set default <CONNECTION_NAME>          set default bearer to <CONNECTION_NAME>
  show default [apn|user|password|all]   show default bearer information
  clear default                          clear default bearer
  version                                display version and exit
  help                                   display help and exit
"

#
# Usage: 4gpi_chat <COMMANDS>
#
4gpi_chat ()
{
  local script

  script="ABORT BUSY ABORT ERROR $*"

  eval chat -t $TIMEOUT $script < $CONSOLE_PORT > $CONSOLE_PORT
}

#
# Usage: 4gpi_echat <COMMANDS>
#
4gpi_echat ()
{
  local script

  script="ABORT BUSY ABORT ERROR $*"

  eval chat -e -t $TIMEOUT $script < $CONSOLE_PORT > $CONSOLE_PORT
}

#
# Usage: nm_show <NAME> [ apn | user | password ]
#
nm_show ()
{
  local cont
  local auth
  local apn
  local user
  local pass

  if [ "$1" != "default" ]
  then
    return 1
  fi

  4gpi_chat "'' AT OK-AT-OK ''"
  cont=$(4gpi_echat "'' AT+CGDCONT? OK ''" 2>&1)
  auth=$(4gpi_echat "'' AT+CGAUTH? OK ''" 2>&1)

  apn=$(echo "$cont" | grep "CGDCONT: 1" | cut -d, -f3 | sed -e 's/"//g')
  user=$(echo "$auth" | grep "CGAUTH: 1" | cut -d, -f3 | sed -e 's/"//g')
  pass=$(echo "$auth" | grep "CGAUTH: 1" | cut -d, -f4 | sed -e 's/"//g')

  case "$2" in
    "apn")
      echo $apn
      ;;
    "user")
      echo $user
      ;;
    "password")
      echo $pass
      ;;
    *)
      echo $apn $user $pass
      ;;
  esac
}

#
# Usage: nm_set <NAME> <FILE_PATH>
#
nm_set ()
{
  local apn
  local user
  local pass
  local default

  if [ "$1" != "default" ]
  then
    return 1
  fi

  apn=$(cat $2 | grep apn | cut -d= -f2)
  if [ "$apn" = "" ]
  then
    echo "no apn found"
    return 1
  fi
  user=$(cat $2 | grep username | cut -d= -f2)
  if [ "$user" = "" ]
  then
    echo "no username found"
    return 1
  fi
  pass=$(cat $2 | grep password | cut -d= -f2)
  if [ "$pass" = "" ]
  then
    echo "no password found"
    return 1
  fi

  default=($(nm_show $1))
  if [ "${default[0]}" = "$apn" ] \
    && [ "${default[1]}" = "$user" ] \
    && [ "${default[2]}" = "$pass" ]
  then
    return 0
  fi

  4gpi_chat "'' AT OK-AT-OK AT+CFUN=4 OK ''"
  4gpi_chat "'' AT+CGDCONT=1,\\\"IPV4V6\\\",\\\"$apn\\\" OK ''"
  4gpi_chat "'' AT+CGAUTH=1,3,\\\"$pass\\\",\\\"$user\\\" OK ''"
  4gpi_chat "'' AT+CFUN=1 OK ''"
}

#
# Usage: nm_clr <NAME>
#
nm_clr ()
{
  if [ "$1" != "default" ]
  then
    return 1
  fi

  4gpi_chat "'' AT OK-AT-OK AT+CFUN=4 OK ''"
  4gpi_chat "'' AT+CGDCONT=1 OK ''"
  4gpi_chat "'' AT+CGAUTH=1 OK ''"
  4gpi_chat "'' AT+CFUN=1 OK ''"
}

[ -r $CONFIG ] && . $CONFIG

#
# execute command
#
case $1 in
show)
  nm_show $2 $3
  ;;
set)
  nm_set $2 $BASE_PATH/$3
  ;;
clear)
  nm_clr $2
  ;;
version)
  echo "4gpi-nm-helper version $VERSION"
  ;;
help)
  echo "$USAGE"
  ;;
*)
  echo "$USAGE"
  exit 1
  ;;
esac
