#!/bin/bash

CONFIG=/etc/default/4gpi
TIMEOUT=10

VERSION="3.0"

USAGE="Usage: 4gpi-nm-helper COMMAND [PARAMETERS...]

Commands:
  set default apn=<apn> [user=<user>] [password=<password>] [pdp=...] [auth=...]
    set default bearer
  Parameters:
    apn=<apn>                set <apn> to APN
    user=<user>              set <user> to user name (optional default blank)
    password=<password>      set <password> to password (optional default blank)
    pdp={IP|IPV6|IPV4V6}     set PDP type (optional default:IPV4V6)
    auth={0|1|2|3}           set authentication type (optional default:3)
      0: none
      1: PAP
      2: CHAP
      3: PAP or CHAP

  show default {apn|user|password|pdp|auth|all}
    show default bearer

  clear default
    clear default bearer

  version
    display version and exit

  help
    display help and exit
"

#
# Usage: 4gpi_chat <COMMANDS>
#
4gpi_chat ()
{
  local script

  script="ABORT BUSY ABORT ERROR $*"

  eval chat -t $TIMEOUT $script < $CONSOLE_PORT > $CONSOLE_PORT
}

#
# Usage: 4gpi_chat_e <COMMANDS>
#
4gpi_chat_e ()
{
  local script

  script="ABORT BUSY ABORT ERROR $*"

  eval chat -e -t $TIMEOUT $script < $CONSOLE_PORT > $CONSOLE_PORT
}

#
# Usage: show_config <NAME> [ apn | user | password | pdp | auth ]
#
show_config ()
{
  local gdcont
  local gauth
  local apn
  local user
  local pass
  local pdp
  local auth

  if [ "$1" != "default" ]
  then
    return 1
  fi

  4gpi_chat "'' AT OK-AT-OK ''"
  gdcont=$(4gpi_chat_e "'' AT+CGDCONT? OK ''" 2>&1 | grep "CGDCONT: 1")
  gauth=$(4gpi_chat_e "'' AT+CGAUTH? OK ''" 2>&1 | grep "CGAUTH: 1")

  apn=$(echo "$gdcont" | cut -d, -f3 | sed -e 's/"//g')
  auth=$(echo "$gauth" | cut -d, -f2 | sed -e 's/"//g')
  user=$(echo "$gauth" | cut -d, -f3 | sed -e 's/"//g')
  pass=$(echo "$gauth" | cut -d, -f4 | sed -e 's/"//g')
  pdp=$(echo "$gdcont" | cut -d, -f2 | sed -e 's/"//g')

  params=($@)
  params=(${params[@]:1})

  if [ ${#params[@]} -eq 0 ]
  then
    params=("all")
  fi

  while [ $params ]
  do
    case "${params[0]}" in
      apn)
        echo $apn
        ;;
      auth)
        echo $auth
        ;;
      user)
        echo $user
        ;;
      password)
        echo $pass
        ;;
      pdp|type)
        echo $pdp
        ;;
      *)
        echo \"$apn\" \"$user\" \"$pass\" \"$pdp\" $auth
        ;;
    esac
    params=(${params[@]:1})
  done
}

#
# Usage: set_config <NAME> <PARAMS...>
#
set_config ()
{
  local apn
  local user
  local pass
  local pdp
  local auth
  local default
  local params

  apn=""
  user=""
  pass=""
  pdp="IPV4V6"
  auth="3"
  params=($@)
  params=(${params[@]:1})

  if [ "$1" != "default" ]
  then
    return 1
  fi

  while [ $params ]
  do
    case "${params[0]}" in
      apn=*)
        apn="$(echo ${params[0]} | sed -e 's/^apn=//')"
        params=(${params[@]:1})
        ;;
      apn)
        apn=${params[1]}
        params=(${params[@]:2})
        ;;
      user=*)
        user="$(echo ${params[0]} | sed -e 's/^user=//')"
        params=(${params[@]:1})
        ;;
      user)
        user=${params[1]}
        params=(${params[@]:2})
        ;;
      password=*)
        pass="$(echo ${params[0]} | sed -e 's/^password=//')"
        params=(${params[@]:1})
        ;;
      password)
        pass=${params[1]}
        params=(${params[@]:2})
        ;;
      pdp=*|type=*)
        pdp="$(echo ${params[0]} | sed -e 's/^pdp=//' -e 's/^type=//')"
        params=(${params[@]:1})
        ;;
      pdp|type)
        pdp=${params[1]}
        params=(${params[@]:2})
        ;;
      auth=*)
        auth="$(echo ${params[0]} | sed -e 's/^auth=//')"
        params=(${params[@]:1})
        ;;
      auth)
        auth=${params[1]}
        params=(${params[@]:2})
        ;;
      *)
        return 1
        ;;
    esac
  done

  current=($(show_config $1))
  if [ "${current[0]}" != "\"$apn\"" ] \
    || [ "${current[3]}" != "\"$pdp\"" ]
  then
    4gpi_chat "'' AT OK-AT-OK AT+CFUN=4 OK ''"
    4gpi_chat "'' AT+CGDCONT=1,\\\"$pdp\\\",\\\"$apn\\\" OK ''"
  fi
  if [ "${current[1]}" != "\"$user\"" ] \
    || [ "${current[2]}" != "\"$pass\"" ] \
    || [ "${current[4]}" != "$auth" ]
  then
    4gpi_chat "'' AT OK-AT-OK AT+CFUN=4 OK ''"
    if [ "$pass" != "" ] && [ "$user" != "" ] && [ "$apn" != "" ]
    then
        4gpi_chat "'' AT+CGAUTH=1,$auth,\\\"$pass\\\",\\\"$user\\\" OK ''"
    else
        4gpi_chat "'' AT+CGAUTH=1 OK ''"
    fi
  fi

  4gpi_chat "'' AT OK-AT-OK AT+CFUN=1 OK ''"
}

#
# Usage: clear_config <NAME>
#
clear_config ()
{
  if [ "$1" != "default" ]
  then
    return 1
  fi

  4gpi_chat "'' AT OK-AT-OK AT+CFUN=4 OK ''"
  4gpi_chat "'' AT+CGDCONT=1 OK ''"
  4gpi_chat "'' AT+CGAUTH=1 OK ''"
  4gpi_chat "'' AT OK-AT-OK AT+CFUN=1 OK ''"
}

[ -r $CONFIG ] && . $CONFIG

args=($@)

#
# execute command
#
case $1 in
  show)
    show_config "$2" "${args[@]:2}"
    ;;
  set)
    set_config "$2" "${args[@]:2}"
    ;;
  clear)
    clear_config "$2"
    ;;
  version)
    echo "4gpi-nm-helper version $VERSION"
    ;;
  help)
    echo "$USAGE"
    ;;
  *)
    echo "$USAGE"
    exit 1
    ;;
esac

