#!/bin/sh

set -e

# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 4gpi-networkmanager-helper.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 4gpi-networkmanager-helper.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 4gpi-networkmanager-helper.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 4gpi-networkmanager-helper.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start 4gpi-networkmanager-helper.service >/dev/null || true
fi

#DEBHELPER#

exit 0
