#!/bin/sh

set -e

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 4gpi-networkmanager-helper.service >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 4gpi-networkmanager-helper.service >/dev/null || true
		deb-systemd-helper unmask 4gpi-networkmanager-helper.service >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
  rm -rf /usr/share/4gpi-networkmanager/__pycache__ || true
fi

#DEBHELPER#

exit 0
